name: torrento
description: An API wrapper for multiple torrent clients to remotely control torrents
version: 0.1.6
homepage: https://github.com/nateshmbhat/torrento

dependencies:
  http: ^0.13.3
  html: ^0.15.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.11.0

environment:
  sdk: '>=2.12.0 <3.0.0'